### ISSUE TITLE
Need an easy way to change year on picking birthday date

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-android-new#103]
For now, we need to tap previous month. Can't find a way to change the year faster.

**Comment by julianmanandhar** [comment]
@tyohan 
currently we are using androids default date-picker widget. we can change the year by tapping on the `year` shown in the top left corner of the widget.

**Comment by julianmanandhar** [comment]
@tyohan 
we have already changed the date picker. could you check and confirm the same.
