### ISSUE TITLE
Related content on content detail

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-android-new#104]
Hi @julianraj @prashantsh, on our latest APK i don't see any related content yet. We have a feature in our CMS to link between content but not shows up in the app. We have this will coming right?

**Comment by julianmanandhar** [comment]
@tyohan is this about the similar audios/videos section??

**Comment by tyohan** [comment]
I thinki it's all to content not only on audio and video. Because the content linked through CMS not from the the PODCast RSS @julianraj

**Comment by julianmanandhar** [comment]
@tyohan 
ok.. will look into it
