### ISSUE TITLE
Having a audio playing backgroud on notification when app closed and audio still playing

### ISSUE THREAD

**Issue by tyohan** [Shuvayatra/migration-android-new#119]
Hi @prashantsh, we're notice that if the audio currently playing and the app closed, the audio keep playing on the background. But somehow user probably will not notice from what app the audio coming. We need to have some information in notification bar to show Shuvayatra app currently playing an audio. May it just contain icon, and title. But better if it can contain audio control.

**Comment by julianmanandhar** [comment]
@tyohan 
will make the necessary changes and inform you once done.

**Comment by tyohan** [comment]
@julianraj i uninstall the previous one then install the latest apk but I can't get the onboarding screen with me. It just logged me in directly with test@shuvayatra.org

**Comment by julianmanandhar** [comment]
@tyohan 
uninstalling should have cleared the data.. will try to figure out whats the cause.
for now you can try clearing the app-data from the app settings.
