### ISSUE TITLE
update API key for open weather

### ISSUE THREAD

**Issue by rakeeb11** [Shuvayatra/migration-android-new#127]
Create an API key for open weather. Used in our country widget for weather forecasts.

**Comment by umuieme** [comment]
@tyohan for the weather api we are using [Open weather](https://openweathermap.org/) and currently using personal API key. So for production you need to provide us the API key by creating your account.

**Comment by rakeeb11** [comment]
@tyohan any updates on this?

**Comment by tyohan** [comment]
@rakeeb11 please use this one b9f726111c15b02aaa2929d83941170e

**Comment by rakeeb11** [comment]
thanks @tyohan.
