### ISSUE TITLE
Facebook share window closes immediately

### ISSUE THREAD

**Issue by benloks** [Shuvayatra/migration-android-new#41]
I'm testing from the apk v0.0.1, and it seems it is not possible to share any items on Facebook. If I click "share," the FB window appears briefly (sometimes half a second, sometimes longer), but closes again before I can type anything or tap "post." This same behavior occurred in the previous version of the app.

Let me know if you need more info.

**Comment by umuieme** [comment]
The app is in development stage. So only the developers are allowed to share the content. If you want to access the functionality now, ask Prashant Shrestha to add you as the developer/tester for the app in facebook developer page. Provide your facebook id also.

**Comment by benloks** [comment]
Understood, thanks.
