### ISSUE TITLE
Top icon not responsive after clicking back to home screen

### ISSUE THREAD

**Issue by benloks** [Shuvayatra/migration-android-new#42]
For example -- if I am on the Home screen and navigate to the Journey tab, the Journey icon lights up. But, when I return to the Home screen by tapping the Shuvayatra icon in the top left, 1) the Journey icon stays lit up, and 2) tapping on the Journey icon again does not allow me to go back to that page.

**Comment by umuieme** [comment]
This issue has been solved

**Comment by benloks** [comment]
Thanks
