### ISSUE TITLE
problem in video playback

### ISSUE THREAD

**Issue by prashantsh** [Shuvayatra/migration-android-new#60]
Video is not playing

**Comment by umuieme** [comment]
The bug lies with the youtube api. The problem is with device youtube app and/or channel. 
Uninstalling the update of youtube will fix the issue.

**Comment by karrbomb** [comment]
I don't understand the bug concept - videos on other YouTube channels play back fine in the app.  Videos uploaded today on other channels play back fine in the app.  If it's an API issue then what is triggering the issue?  YouTube videos that are loaded into CMS today and reside on other channels play back in the app.  I would suggest we examine the Shuvayatra YouTube page settings.
